name: Brix-Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      CCI_VERSION:
        type: string
        default: "quasar"
        description: "The version of the CCI to use"
      QX_VERSION:
        type: string
        default: "main"
        description: "The version of the QX to use"

env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  SFDX_CLIENT_ID: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  SFDX_HUB_KEY: ${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}
  DEVHUBCONSUMERKEY: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  DEVHUBJWTKEYFILE: devhub.key
  GITHUB_PAT: ${{ secrets.QBRIX_GITHUB_PAT}}
  QBRIX_CONTAINER_PUBLISH_GITHUB_PAT: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT }}
  SFDX_DISABLE_DNS_CHECK: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  QBRIX_SYSTEM_ID: GIT_BUILD_AUTOMATION
  SF_USE_PROGRESS_BAR: false
  QSR_ENDPOINT: ${{ secrets.QSR_ENDPOINT }}
  QSR_JWT_SIGNING_SECRET: ${{ secrets.QSR_JWT_SIGNING_SECRET }}
  USER: ${{github.actor}}
  ORG_TARGET_USER:
  BUILD_SUFFIX:
  REPO_NAME:
  AUTOPUBLISH:
  AUTODEPLOY_STATUS:
  CUMULUSCI_SERVICE_github: ${{ secrets.QBRIX_CUMULUSCI_SERVICE_github }}
  REMOTE_CONTAINERS: True
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  ENABLE_FLOW_STATE_TRACKING: ${{ vars.ENABLE_FLOW_STATE_TRACKING }}
  OTEL_SDK_DISABLED: ${{ vars.OTEL_SDK_DISABLED }}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}
  CCI_VERSION: ${{ github.event.inputs.CCI_VERSION || vars.CCI_VERSION || 'quasar' }}
  QX_VERSION: ${{ github.event.inputs.QX_VERSION || vars.QX_VERSION || 'main' }}  


jobs:
    qlabs_publish:
        if: (github.ref_name == 'master' || github.ref_name == 'main')
        uses: sfdc-qbranch-emu/qbrix-0-automatrix/.github/workflows/brix-build-qlabs-publish.yml@main
        secrets: inherit
        with:
          repository_name: ${{ github.event.repository.name }}
          repository_id: ${{ github.repository_id }}
          repository_url: ${{ github.repositoryUrl }}
          sha: ${{ github.sha }}
          ref_name: ${{ github.ref_name }}
          event_name: ${{ github.event_name }}

    qlabs_publish_keywords:
        if: (github.ref_name == 'master' || github.ref_name == 'main')
        uses: sfdc-qbranch-emu/qbrix-0-automatrix/.github/workflows/brix-build-publish-keywords.yml@main
        secrets: inherit
        with:
          repository_name: ${{ github.event.repository.name }}
          qx_version: ${{ github.event.inputs.QX_VERSION || vars.QX_VERSION || 'main' }}

    required_builds:
        if: (always() && (needs.qlabs_publish.result == 'success' || needs.qlabs_publish.result == 'skipped'))
        needs: qlabs_publish
        uses: sfdc-qbranch-emu/qbrix-0-automatrix/.github/workflows/brix-build-matrix.yml@main
        secrets: inherit
        with:
            repository: ${{ github.repository }}
            repository_id: ${{ github.repository_id }}
            repository_owner: ${{ github.repository_owner }}
            build_base_container: ${{ vars.BUILD_BASE_CONTAINER }}
            qx_version: ${{ github.event.inputs.QX_VERSION || vars.QX_VERSION || 'main' }}
            cci_version: ${{ github.event.inputs.CCI_VERSION || vars.CCI_VERSION || 'quasar' }}

    optional_builds:
        if: always() && (needs.qlabs_publish.result == 'success' || needs.qlabs_publish.result == 'skipped')
        needs: qlabs_publish
        uses: sfdc-qbranch-emu/qbrix-0-automatrix/.github/workflows/brix-build-hybrid-build-matrix.yml@main
        secrets: inherit
        with:
            repository: ${{ github.repository }}
            repository_id: ${{ github.repository_id }}
            repository_owner: ${{ github.repository_owner }}
            build_base_container: ${{ vars.BUILD_BASE_CONTAINER }}
            qx_version: ${{ github.event.inputs.QX_VERSION || vars.QX_VERSION || 'main' }}
            cci_version: ${{ github.event.inputs.CCI_VERSION || vars.CCI_VERSION || 'quasar' }}
    
    leafshake_builds:
        if: |
            always() &&
            (github.event.pull_request.head.ref != '' || github.ref_name == 'main') && 
            needs.required_builds.result == 'success'
        needs: [required_builds]
        uses: sfdc-qbranch-emu/qbrix-0-automatrix/.github/workflows/brix-build-leafshake-build-matrix.yml@main
        secrets: inherit
        with:
            repository: ${{ github.repository }}
            repository_id: ${{ github.repository_id }}
            repository_owner: ${{ github.repository_owner }}
            build_base_container: ${{ vars.BUILD_BASE_CONTAINER }}
            qx_version: ${{ github.event.inputs.QX_VERSION || vars.QX_VERSION || 'main' }}
            cci_version: ${{ github.event.inputs.CCI_VERSION || vars.CCI_VERSION || 'quasar' }}
            pull_request_head_ref: ${{ github.event.pull_request.head.ref }}

    autodeploy_matrix:
        needs: [leafshake_builds, required_builds]
        if: always() && (needs.required_builds.result=='success') && (github.ref_name == 'main' || github.ref_name == 'master') && (needs.leafshake_builds.result == 'success' || needs.leafshake_builds.result == 'skipped' || needs.leafshake_builds.result == 'failed')
        uses: sfdc-qbranch-emu/qbrix-0-automatrix/.github/workflows/brix-build-autodeploy-matrix.yml@main
        secrets: inherit
        with:
            repository: ${{ github.repository }}
            repository_id: ${{ github.repository_id }}
            repository_owner: ${{ github.repository_owner }}
            build_base_container: ${{ vars.BUILD_BASE_CONTAINER }}
            qx_version: ${{ github.event.inputs.QX_VERSION || vars.QX_VERSION || 'main' }}
            cci_version: ${{ github.event.inputs.CCI_VERSION || vars.CCI_VERSION || 'quasar' }}
            is_hybrid: false

    hybrid_autodeploy_matrix:
        needs: [leafshake_builds, required_builds]
        if: always() && (needs.required_builds.result=='success') && (github.ref_name == 'main' || github.ref_name == 'master') && (needs.leafshake_builds.result == 'success' || needs.leafshake_builds.result == 'skipped' || needs.leafshake_builds.result == 'failed')
        uses: sfdc-qbranch-emu/qbrix-0-automatrix/.github/workflows/brix-build-autodeploy-matrix.yml@main
        secrets: inherit
        with:
            repository: ${{ github.repository }}
            repository_id: ${{ github.repository_id }}
            repository_owner: ${{ github.repository_owner }}
            build_base_container: ${{ vars.BUILD_BASE_CONTAINER }}
            qx_version: ${{ github.event.inputs.QX_VERSION || vars.QX_VERSION || 'main' }}
            cci_version: ${{ github.event.inputs.CCI_VERSION || vars.CCI_VERSION || 'quasar' }}
            is_hybrid: true