name: Brix-Build
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  SFDX_CLIENT_ID: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  SFDX_HUB_KEY: ${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}
  DEVHUBCONSUMERKEY: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  DEVHUBJWTKEYFILE: devhub.key
  GITHUB_PAT: ${{ secrets.QBRIX_GITHUB_PAT}}
  SFDX_DISABLE_DNS_CHECK: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  QBRIX_SYSTEM_ID: GIT_BUILD_AUTOMATION
  SF_USE_PROGRESS_BAR: false
  QSR_ENDPOINT: ${{ secrets.QSR_ENDPOINT }}
  QSR_JWT_SIGNING_SECRET: ${{ secrets.QSR_JWT_SIGNING_SECRET }}
  USER: ${{github.actor}}
  ORG_TARGET_USER:
  BUILD_SUFFIX:
  REPO_NAME:
  AUTOPUBLISH:
  AUTODEPLOY_STATUS:
  CUMULUSCI_SERVICE_metadeploy: '{"url":"${{secrets.QBRIX_CUMULUSCI_SERVICE_METADEPLOY_URL}}","token": "${{secrets.QBRIX_CUMULUSCI_SERVICE_METADEPLOY_TOKEN}}"}'
  CUMULUSCI_SERVICE_github: ${{ secrets.QBRIX_CUMULUSCI_SERVICE_github }}
  REMOTE_CONTAINERS: True
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  ENABLE_FLOW_STATE_TRACKING: ${{ vars.ENABLE_FLOW_STATE_TRACKING }}
  OTEL_SDK_DISABLED: ${{ vars.OTEL_SDK_DISABLED }}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}


jobs:
  qlabs_publish:
    if: (github.ref_name == 'master' || github.ref_name == 'main')
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    steps:
      - uses: actions/checkout@v4

      - name: Core Setup - key for jwt auth
        run: echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        id: qlabs_accesstoken
        run: |
          jq '.result.accessToken' qlab_tmp.json -r
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      - name: Install PYYaml
        run: python3 -m pip install pyyaml

      - name: Write python File
        id: create_publish_file
        run: |
          cat << EOF > qlab_publish.py
          import yaml
          import os
          import requests
          import jwt
          import json
          def getAuth(user:str):
            QSR_JWT_SIGNING_SECRET = os.environ.get('QSR_JWT_SIGNING_SECRET')
            encoded_jwt = jwt.encode({"sub": f"{user}", "external_id": f"{user}", "aud": f"{user}"},QSR_JWT_SIGNING_SECRET, algorithm="HS256")
            return encoded_jwt

          def refreshQBrix(qbrix:str):
            url = os.environ.get('QSR_ENDPOINT')
            payload = json.dumps({
                "qbrix": f"{qbrix}"
            })
            print(payload)
            headers = {
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {getAuth(os.environ.get("USER"))}'
            }
            response = requests.request("DELETE", url, headers=headers, data=payload)
            response = requests.request("PUT", url, headers=headers, data=payload)


          refreshQBrix('${{ github.event.repository.name }}')
          filepath='cumulusci.yml'
          inputsfile = 'qbrix_local/inputs/required.json'
          if(os.path.isfile(filepath)):
              with open(filepath, 'r') as stream:
                yamldata = yaml.safe_load(stream)
                url = "https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixContentService"

                payload = json.dumps(yamldata)
                payloaddic = json.loads(payload)
                print(type(payload))
                payloaddic["github_repository_id"] = "${{ github.repository_id }}"
                payloaddic["github_repository_url"] = "${{ github.repositoryUrl }}"
                payloaddic["github_sha"] = "${{ github.sha }}"
                payload=json.dumps(payloaddic)

                #check for a required parameters object
                if (os.path.isfile(inputsfile)):
                  inputcontent = open(inputsfile, "r")
                  inputjson = inputcontent.read()
                  inputsdict = json.loads(inputjson)

                  if("parameters" in inputsdict):
                    print('Parameters found')
                    print(payload)
                    tempPayload=json.loads(payload)
                    tempPayload["parameters"]=inputsdict["parameters"]
                    payload=json.dumps(tempPayload)

                headers = {
                    'Authorization': 'Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken  }}',
                    'Content-Type': 'application/json'
                }
                requests.request("POST", url, headers=headers, data=payload)
          EOF

      - name: Run the publish
        run: python3 qlab_publish.py

  setup_build_steps:
    if: |
      always() &&
      (needs.qlabs_publish.result == 'success' || needs.qlabs_publish.result == 'skipped') &&
      ! contains(github.repository, '-7-')
    needs: [qlabs_publish]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    outputs:
      matrix: ${{ steps.set-build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set ENV variables
        run: |
          echo "::set-env name=REPO_NAME::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"

      - name: Set ownership
        id: set_ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Core Setup - key for jwt auth
        run: |
          echo '${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}' > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        id: qlabs_accesstoken
        run: |
          jq '.result.accessToken' qlab_tmp.json -r
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

        #Update the build Status to Running only on the main or master branch
      - name: clear legacy build matrice results
        if: github.ref_name == 'main' || github.ref_name == 'master'
        run: |
          curl --location --request DELETE 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{"brixname": "${{ env.REPO_NAME }}"}'

        #Update the build Status to Running only on the main or master branch
      - name: get the build matrices
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixBuildMatrixService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{"brixname": "${{ env.REPO_NAME }}"}' -o full_matrix.json

      - name: parse build matrices
        run: |
          jq '.builds' full_matrix.json > matrix_build.json

      - name: Check file existence
        id: collection_run_present
        run: |
          if [ -f matrix_build.json ]; then
              echo "files_exists=true" >> "$GITHUB_OUTPUT"
          else
              echo "files_exists=false" >> "$GITHUB_OUTPUT"
              echo '[{ "build": "", "build_action_type": "","build_action":"","isscratch":"false","description":"" }]' > matrix_build.json
          fi

      - name: load run matrix for the defined build matrix
        id: set-build-matrix
        run: |
          echo "matrix={\"include\":$(jq -c '.' matrix_build.json -r)}" >> $GITHUB_OUTPUT

  setup_hybrid_build_steps:
    if: |
      always() &&
      (needs.qlabs_publish.result == 'success' || needs.qlabs_publish.result == 'skipped') &&
      ! contains(github.repository, '-7-')
    needs: [qlabs_publish]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    outputs:
      matrix: ${{ steps.set-build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set ENV variables
        run: |
          echo "::set-env name=REPO_NAME::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"

      - name: Set ownership
        id: set_ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Core Setup - key for jwt auth
        run: |
          echo '${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}' > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        id: qlabs_accesstoken
        run: |
          jq '.result.accessToken' qlab_tmp.json -r
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

        #Update the build Status to Running only on the main or master branch
      - name: get the build matrices
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixBuildMatrixService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{"brixname": "${{ env.REPO_NAME }}"}' -o full_matrix.json

      - name: parse build matrices
        run: |
          jq '.hybridbuilds' full_matrix.json > matrix_build.json

      - name: Check file existence
        id: collection_run_present
        run: |
          if [ -f matrix_build.json ]; then
              echo "files_exists=true" >> "$GITHUB_OUTPUT"
          else
              echo "files_exists=false" >> "$GITHUB_OUTPUT"
              echo '[{ "build": "", "build_action_type": "","build_action":"","isscratch":"false","description":"" }]' > matrix_build.json
          fi

      - name: load run matrix for the defined build matrix
        id: set-build-matrix
        run: |
          echo "matrix={\"include\":$(jq -c '.' matrix_build.json -r)}" >> $GITHUB_OUTPUT

  build_deployments:
    if: |
      always() &&
      needs.setup_build_steps.result == 'success' &&
      ! contains(github.repository, '-7-')
    needs: [setup_build_steps]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup_build_steps.outputs.matrix) }}
      max-parallel: 250 #run in sequence
    name: 'Required: ${{matrix.description}} - ${{matrix.templateid}}'

    steps:
      - uses: actions/checkout@v4

      - name: Update QX
        run: qx update

      - name: Set ENV variables
        run: |
          echo "::set-env name=REPO_NAME::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          # assume might have been updated

      - name: Download Repo for the matrix::${{matrix.reference_brix}} and setup runtime
        id: qlabs_accesstoken
        run: |
          echo "::set-env name=BUILD_SUFFIX::${{ matrix.build }}"
          pwd
          ls -l
          echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key
          sf org login jwt -o ${{ secrets.QBRIX_DEVHUB_USERACCOUNT }} -a DEVHUB_ACCT -d -f devhub.key -i '${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}'
          sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i '${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}'
          sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json
          jq '.result.accessToken' qlab_tmp.json -r
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      #Update the build Status to Running only on the main or master branch
      - name: update build status to starting
        if: (github.ref_name == 'master' || github.ref_name == 'main')
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.build }}",
              "leafshakebrixname": "${{github.ref_name}}",
              "buildstatus": "Running",
              "details": ""
            }'

      #determine if there is a template or instance override defined in qlabs for this build config
      - name: get qlabs config settings
        id: qlab_config_settings
        run: |
          # call qlabs setting service for this qbrix -> get the json -> pipe to jq
          curl --location --request GET 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixBuildServiceProperties?workflowconfigid=${{ env.REPO_NAME }}-${{ matrix.build }}&templateid=${{matrix.templateid}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' | jq > qlab_settings.json
          echo "TEMPLATEID=$(jq '.templateid' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "TEMPLATEID=$(jq '.templateid' qlab_settings.json -r)" >> "$GITHUB_ENV"
          echo "TEMPLATE_INSTANCE=$(jq '.template_instance' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "TEMPLATE_INSTANCE=$(jq '.template_instance' qlab_settings.json -r)" >> "$GITHUB_ENV"
          echo "ORG_TARGET_USER=$(jq '.org_target_user' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "ORG_TARGET_USER=$(jq '.org_target_user' qlab_settings.json -r)" >> "$GITHUB_ENV"

      - name: Set CCI DevHub Username
        run: |
          cci service connect devhub --username DEVHUB_ACCT

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        run: |
          cci service list

      - name: Pre Check Command path
        run: |
          cci ${{ matrix.build_action_type }} info ${{ matrix.build_action }}

        # Create a scratch org to attach - future use the org pool service
      - name: generate scratch org ${{ matrix.isscratch }}- if the evn variable to use a template is set to false - we fallback to org/dev.json - ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}
        if: matrix.isscratch == 'true' && steps.qlab_config_settings.outputs.ORG_TARGET_USER == ''
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 5
          retry_on: error
          command: |
            cci task run spin_request --maxwait 120 --mode SCRATCH --scratch_config orgs/dev.json --devhubuser DEVHUB_ACCT --cciorg ninja --devhubconsumerkey ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }} --devhubjwtkeyfile devhub.key

      - name: generate production org ${{ matrix.isscratch }} - if the evn variable to use a template is set to true - we connect to the devhub that is enabled to provision an org - ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}
        if: matrix.isscratch  == 'false'  && steps.qlab_config_settings.outputs.ORG_TARGET_USER == ''
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 3
          retry_on: error
          command: |
            cci task run spin_request --maxwait 120 --mode TEMPLATE --cciorg ninja --devhubuser DEVHUB_ACCT --instance ${{steps.qlab_config_settings.outputs.TEMPLATE_INSTANCE}} --devhubconsumerkey ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }} --devhubjwtkeyfile devhub.key --templateid ${{ steps.qlab_config_settings.outputs.TEMPLATE_ID }}

      - name: The central QLabs Settings has specified dedicated org/user to run against.
        if: (${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}!='')
        run: |
          sf org login jwt -o ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }} -a dev_target_username -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
          cci org import ${{steps.qlab_config_settings.outputs.ORG_TARGET_USER}} ninja

      - name: export cci session data
        run: |
          cci org info ninja --json > targetdev.json
          tail -n +1 targetdev.json
          tail -n +1 targetdev.json > targetorg.json

      - name: extract the target user
        id: extrattargetorg
        run: |
          echo "extrattargetorg=$(jq '.username' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: extract the target accesstoken
        id: extrattargetaccesstoken
        run: |
          echo "extrattargetaccesstoken=$(jq '.access_token' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: extract the target accesstoken
        id: extrattargetinstanceurl
        run: |
          echo "extrattargetinstanceurl=$(jq '.instance_url' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: set output target user
        id: loadtargetorg
        run: |
          echo "target-org=${{ steps.extrattargetorg.outputs.extrattargetorg }}" >> $GITHUB_OUTPUT

      - name: set output target access token
        id: loadtargetaccesstoken
        run: |
          echo "target-accesstoken=${{ steps.extrattargetaccesstoken.outputs.extrattargetaccesstoken }}" >> $GITHUB_OUTPUT

      - name: set output target instance url
        id: loadtargetintanceurl
        run: |
          echo "target-instanceurl=${{ steps.extrattargetinstanceurl.outputs.extrattargetinstanceurl }}" >> $GITHUB_OUTPUT

      - name: fail details
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        id: cci_failure_details
        run: |
          echo "cci_failure_details=$(cci error info | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: fail status
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.build }}",
              "leafshakebrixname": "${{github.ref_name}}",
              "buildstatus": "Failed",
              "details": "${{ steps.cci_failure_details.outputs.cci_failure_details }}"
          }'

      - name: rfbrowser init setup
        run: |
          pip install protobuf==5.28.1 --force
          rfbrowser init

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        run: |
          cci service list
          cci org info ninja

      - name: Running ${{ matrix.description }} ${{ matrix.build_action }}::${{ matrix.build_action_type }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: |
            cci ${{ matrix.build_action_type }} run ${{ matrix.build_action }}  --org ninja
          on_retry_command: cci error info

      - name: Running Validate
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: |
            cci flow run validate_qbrix  --org ninja
          on_retry_command: cci error info

      - name: Check file existence
        id: check_validationresults_present
        run: |
          pwd
          ls -la
          if test -f validationresult.json; then
            echo "files_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Read Validation Results file - if present
        if: steps.check_validationresults_present.outputs.files_exists == 'true'
        id: read_validationresults_file
        run: |
          echo "read_validationresults_file=$(cat validationresult.json)" >> "$GITHUB_OUTPUT"

      - name: upload the validation results - if present
        if: ((github.ref_name == 'master' || github.ref_name == 'main') && steps.check_validationresults_present.outputs.files_exists == 'true')
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixValidationService/${{ github.repository }}-${{ matrix.build }}-${{github.ref_name}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '${{ steps.read_validationresults_file.outputs.read_validationresults_file }}'

      - name: clear existing validation results - not file present
        if: ((github.ref_name == 'master' || github.ref_name == 'main') && steps.check_validationresults_present.outputs.files_exists == 'false')
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixValidationService/${{ github.repository }}-${{ matrix.build }}-${{github.ref_name}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{"results":[]}'

      - name: success status
        if: (success() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "github_repository_id": "${{ github.repository_id }}",
            "brixname": "${{ github.repository }}",
            "leafshakebrixbuildname": "${{ matrix.build }}",
            "leafshakebrixname": "${{github.ref_name}}",
            "buildstatus": "Passed",
            "details": ""
                }'

      - name: fail details - final
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        id: cci_failure_details_final
        run: |
          echo "cci_failure_details_final=$(cci error info | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: fail status
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.build }}",
              "leafshakebrixname": "${{github.ref_name}}",
              "buildstatus": "Failed",
              "details": "${{ steps.cci_failure_details_final.outputs.cci_failure_details_final }}"
          }'

  hybrid_org_build_deployments:
    if: |
      always() &&
      needs.setup_hybrid_build_steps.result == 'success' &&
      needs.setup_hybrid_build_steps.outputs.matrix!='{"include":[]}' &&
      needs.setup_hybrid_build_steps.outputs.matrix != '' &&
      ! contains(github.repository, '-7-')
    needs: [setup_hybrid_build_steps]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    continue-on-error: true
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup_hybrid_build_steps.outputs.matrix) }}
      max-parallel: 250 #run in sequence
    name: 'Optional: ${{matrix.description}} - ${{matrix.templateid}}'
    steps:
      - uses: actions/checkout@v4

      - name: Update QX
        run: qx update

      - name: Set ENV variables
        run: |
          echo "::set-env name=REPO_NAME::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          # assume might have been updated

      - name: Download Repo for the matrix::${{matrix.reference_brix}} and setup runtime
        id: qlabs_accesstoken
        run: |
          echo "::set-env name=BUILD_SUFFIX::${{ matrix.build }}"
          pwd
          ls -l
          echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key
          sf org login jwt -o ${{ secrets.QBRIX_DEVHUB_USERACCOUNT }} -a DEVHUB_ACCT -d -f devhub.key -i '${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}'
          sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i '${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}'
          sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json
          jq '.result.accessToken' qlab_tmp.json -r
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      #Update the build Status to Running only on the main or master branch
      - name: update build status to starting
        if: (github.ref_name == 'master' || github.ref_name == 'main')
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.build }}",
              "leafshakebrixname": "${{github.ref_name}}",
              "buildstatus": "Running",
              "details": ""
            }'

      #determine if there is a template or instance override defined in qlabs for this build config
      - name: get qlabs config settings
        id: qlab_config_settings
        run: |
          # call qlabs setting service for this qbrix -> get the json -> pipe to jq
          curl --location --request GET 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixBuildServiceProperties?workflowconfigid=${{ env.REPO_NAME }}-${{ matrix.build }}&templateid=${{matrix.templateid}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' | jq > qlab_settings.json
          echo "TEMPLATEID=$(jq '.templateid' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "TEMPLATEID=$(jq '.templateid' qlab_settings.json -r)" >> "$GITHUB_ENV"
          echo "TEMPLATE_INSTANCE=$(jq '.template_instance' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "TEMPLATE_INSTANCE=$(jq '.template_instance' qlab_settings.json -r)" >> "$GITHUB_ENV"
          echo "ORG_TARGET_USER=$(jq '.org_target_user' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "ORG_TARGET_USER=$(jq '.org_target_user' qlab_settings.json -r)" >> "$GITHUB_ENV"

      - name: Set CCI DevHub Username
        run: |
          cci service connect devhub --username DEVHUB_ACCT

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        run: |
          cci service list

      - name: Pre Check Command path
        run: |
          cci ${{ matrix.build_action_type }} info ${{ matrix.build_action }}

        # Create a scratch org to attach - future use the org pool service
      - name: generate scratch org ${{ matrix.isscratch }}- if the evn variable to use a template is set to false - we fallback to org/dev.json - ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}
        if: matrix.isscratch == 'true' && steps.qlab_config_settings.outputs.ORG_TARGET_USER == ''
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 5
          retry_on: error
          command: |
            cci task run spin_request --maxwait 120 --mode SCRATCH --scratch_config orgs/dev.json --devhubuser DEVHUB_ACCT --cciorg ninja --devhubconsumerkey ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }} --devhubjwtkeyfile devhub.key

      - name: generate production org ${{ matrix.isscratch }} - if the evn variable to use a template is set to true - we connect to the devhub that is enabled to provision an org - ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}
        if: matrix.isscratch  == 'false'  && steps.qlab_config_settings.outputs.ORG_TARGET_USER == ''
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 3
          retry_on: error
          command: |
            cci task run spin_request --maxwait 120 --mode TEMPLATE --cciorg ninja --devhubuser DEVHUB_ACCT --instance ${{steps.qlab_config_settings.outputs.TEMPLATE_INSTANCE}} --devhubconsumerkey ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }} --devhubjwtkeyfile devhub.key --templateid ${{ steps.qlab_config_settings.outputs.TEMPLATE_ID }}

      - name: The central QLabs Settings has specified dedicated org/user to run against.
        if: (${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}!='')
        run: |
          sf org login jwt -o ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }} -a dev_target_username -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
          cci org import ${{steps.qlab_config_settings.outputs.ORG_TARGET_USER}} ninja

      - name: export cci session data
        run: |
          cci org info ninja --json > targetdev.json
          tail -n +1 targetdev.json
          tail -n +1 targetdev.json > targetorg.json

      - name: extract the target user
        id: extrattargetorg
        run: |
          echo "extrattargetorg=$(jq '.username' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: extract the target accesstoken
        id: extrattargetaccesstoken
        run: |
          echo "extrattargetaccesstoken=$(jq '.access_token' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: extract the target accesstoken
        id: extrattargetinstanceurl
        run: |
          echo "extrattargetinstanceurl=$(jq '.instance_url' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: set output target user
        id: loadtargetorg
        run: |
          echo "target-org=${{ steps.extrattargetorg.outputs.extrattargetorg }}" >> $GITHUB_OUTPUT

      - name: set output target access token
        id: loadtargetaccesstoken
        run: |
          echo "target-accesstoken=${{ steps.extrattargetaccesstoken.outputs.extrattargetaccesstoken }}" >> $GITHUB_OUTPUT

      - name: set output target instance url
        id: loadtargetintanceurl
        run: |
          echo "target-instanceurl=${{ steps.extrattargetinstanceurl.outputs.extrattargetinstanceurl }}" >> $GITHUB_OUTPUT

      - name: fail details
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        id: cci_failure_details
        run: |
          echo "cci_failure_details=$(cci error info | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: fail status
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.build }}",
              "leafshakebrixname": "${{github.ref_name}}",
              "buildstatus": "Failed",
              "details": "${{ steps.cci_failure_details.outputs.cci_failure_details }}"
          }'

      - name: rfbrowser init setup
        run: |
          pip install protobuf==5.28.1 --force
          rfbrowser init

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        run: |
          cci service list
          cci org info ninja

      - name: Running ${{ matrix.description }} ${{ matrix.build_action }}::${{ matrix.build_action_type }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: |
            cci ${{ matrix.build_action_type }} run ${{ matrix.build_action }}  --org ninja
          on_retry_command: cci error info

      - name: Running Validate
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: |
            cci flow run validate_qbrix  --org ninja
          on_retry_command: cci error info

      - name: Check file existence
        id: check_validationresults_present
        run: |
          pwd
          ls -la
          if test -f validationresult.json; then
            echo "files_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Read Validation Results file - if present
        if: steps.check_validationresults_present.outputs.files_exists == 'true'
        id: read_validationresults_file
        run: |
          echo "read_validationresults_file=$(cat validationresult.json)" >> "$GITHUB_OUTPUT"

      - name: upload the validation results - if present
        if: ((github.ref_name == 'master' || github.ref_name == 'main') && steps.check_validationresults_present.outputs.files_exists == 'true')
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixValidationService/${{ github.repository }}-${{ matrix.build }}-${{github.ref_name}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '${{ steps.read_validationresults_file.outputs.read_validationresults_file }}'

      - name: clear existing validation results - not file present
        if: ((github.ref_name == 'master' || github.ref_name == 'main') && steps.check_validationresults_present.outputs.files_exists == 'false')
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixValidationService/${{ github.repository }}-${{ matrix.build }}-${{github.ref_name}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{"results":[]}'

      - name: success status
        if: (success() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "github_repository_id": "${{ github.repository_id }}",
            "brixname": "${{ github.repository }}",
            "leafshakebrixbuildname": "${{ matrix.build }}",
            "leafshakebrixname": "${{github.ref_name}}",
            "buildstatus": "Passed",
            "details": ""
                }'

      - name: fail details - final
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        id: cci_failure_details_final
        run: |
          echo "cci_failure_details_final=$(cci error info | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: fail status
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.build }}",
              "leafshakebrixname": "${{github.ref_name}}",
              "buildstatus": "Failed",
              "details": "${{ steps.cci_failure_details_final.outputs.cci_failure_details_final }}"
          }'

  setup_leafshake_steps:
    if: |
      always() &&
      (github.event.pull_request.head.ref != '' || github.ref_name == 'main') &&
      needs.build_deployments.result == 'success' &&
      ! contains(github.repository, '-7-')
    needs: [build_deployments]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    outputs:
      matrix: ${{ steps.set-leaf-shake-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set ENV variables
        run: |
          echo "::set-env name=REPO_NAME::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"

      - name: Set ownership
        id: set_ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Core Setup - key for jwt auth
        run: |
          echo '${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}' > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        id: qlabs_accesstoken
        run: |
          jq '.result.accessToken' qlab_tmp.json -r
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

        #Update the build Status to Running only on the main or master branch
      - name: get the build matrices
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixBuildMatrixService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{"brixname": "${{ env.REPO_NAME }}"}' -o full_matrix.json

      - name: load run matrix for the defined leaf shaking
        id: set-leaf-shake-matrix
        run: |
          echo "matrix={\"include\":$(jq -c '.leafshake' full_matrix.json -r)}" >> $GITHUB_OUTPUT

  leaf_shake_deployments:
    needs: [setup_leafshake_steps]
    if: |
      always() &&
      (github.event.pull_request.head.ref != '' || github.ref_name == 'main') &&
      (needs.setup_leafshake_steps.result == 'success' || needs.setup_leafshake_steps.result == 'skipped' )&&
      needs.setup_leafshake_steps.outputs.matrix!='{"include":[]}' &&
      needs.setup_leafshake_steps.outputs.matrix != '' &&
      ! contains(github.repository, '-7-')
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup_leafshake_steps.outputs.matrix) }}
      max-parallel: 250 #run in sequence
    name: '${{matrix.reference_brix}} - ${{matrix.templateid}}'
    steps:
      #- uses: actions/checkout@v4
      - name: Clone Reference Brix for Leaf Shake Build
        run: |
          git clone https://${{ secrets.QBRIX_GITHUB_PAT}}:x-oauth-basic@github.com/${{github.repository_owner}}/${{matrix.reference_brix}}

      - name: Update QX
        run: qx update

      - name: Set ENV variables
        run: |
          echo "::set-env name=REPO_NAME::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          cd ${{matrix.reference_brix}}
          chown -R $(id -u):$(id -g) $PWD

      - name: Download Repo for the matrix::${{matrix.reference_brix}} and setup runtime
        id: qlabs_accesstoken
        run: |
          cd ${{matrix.reference_brix}}
          echo "::set-env name=BUILD_SUFFIX::${{ matrix.reference_brix_leafshake_build }}"
          pwd
          ls -l
          echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key
          sf org login jwt -o ${{ secrets.QBRIX_DEVHUB_USERACCOUNT }} -a DEVHUB_ACCT -d -f devhub.key -i '${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}'
          sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i '${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}'
          sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json
          jq '.result.accessToken' qlab_tmp.json -r
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      #Update the build Status to Running only on the main or master branch
      - name: update build status to starting
        if: (github.ref_name == 'master' || github.ref_name == 'main')
        run: |
          cd ${{matrix.reference_brix}}
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.reference_brix_leafshake_build }}",
              "leafshakebrixname": "${{matrix.reference_brix}}",
              "buildstatus": "Running",
              "details": ""
            }'

      #determine if there is a template or instance override defined in qlabs for this build config
      - name: get qlabs config settings
        id: qlab_config_settings
        run: |
          cd ${{matrix.reference_brix}}
          # call qlabs setting service for this qbrix -> get the json -> pipe to jq
          curl --location --request GET 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixBuildServiceProperties?workflowconfigid=${{ matrix.reference_brix }}-${{ matrix.reference_brix_leafshake_build }}&templateid=${{matrix.templateid}}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' | jq > qlab_settings.json
          echo "TEMPLATEID=$(jq '.templateid' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "TEMPLATEID=$(jq '.templateid' qlab_settings.json -r)" >> "$GITHUB_ENV"
          echo "TEMPLATE_INSTANCE=$(jq '.template_instance' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "TEMPLATE_INSTANCE=$(jq '.template_instance' qlab_settings.json -r)" >> "$GITHUB_ENV"
          echo "ORG_TARGET_USER=$(jq '.org_target_user' qlab_settings.json -r)" >> "$GITHUB_OUTPUT"
          echo "ORG_TARGET_USER=$(jq '.org_target_user' qlab_settings.json -r)" >> "$GITHUB_ENV"

      - name: Set CCI DevHub Username
        run: |
          cd ${{matrix.reference_brix}}
          cci service connect devhub --username DEVHUB_ACCT

      - name: Drop Leaf
        run: |
          cd ${{matrix.reference_brix}}
          [ -e QUASAR_LEAF_SHAKE ] && rm QUASAR_LEAF_SHAKE
          jq -n '{"${{env.REPO_NAME}}":"${{github.event.pull_request.head.ref || github.ref_name}}"}' > QUASAR_LEAF_SHAKE
          echo $(cat QUASAR_LEAF_SHAKE)
          pwd
          ls -l

      - name: All connected services
        run: |
          cd ${{matrix.reference_brix}}
          cci service list

      - name: Pre Check Command path
        run: |
          cd ${{matrix.reference_brix}}
          cci ${{ matrix.leaf_shake_action_type }} info ${{ matrix.leaf_shake_action }}

        # Create a scratch org to attach - future use the org pool service
      - name: generate scratch org ${{ matrix.isscratch }}- if the evn variable to use a template is set to false - we fallback to org/dev.json - ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}
        if: ((matrix.isscratch == 'true') && (steps.qlab_config_settings.outputs.ORG_TARGET_USER ==''))
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 5
          retry_on: error
          command: |
            cd ${{matrix.reference_brix}}
            cci task run spin_request --maxwait 120 --mode SCRATCH --scratch_config orgs/dev.json --devhubuser DEVHUB_ACCT --cciorg ninja --devhubconsumerkey ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }} --devhubjwtkeyfile devhub.key

      - name: generate production org ${{ matrix.isscratch }} - if the evn variable to use a template is set to true - we connect to the devhub that is enabled to provision an org - ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}
        if: ((matrix.isscratch  == 'false' ) && (steps.qlab_config_settings.outputs.ORG_TARGET_USER ==''))
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 3
          retry_on: error
          command: |
            cd ${{matrix.reference_brix}}
            cci task run spin_request --maxwait 120 --mode TEMPLATE --cciorg ninja --devhubuser DEVHUB_ACCT --instance ${{steps.qlab_config_settings.outputs.TEMPLATE_INSTANCE}} --devhubconsumerkey ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }} --devhubjwtkeyfile devhub.key --templateid ${{ steps.qlab_config_settings.outputs.TEMPLATE_ID }}

      - name: The central QLabs Settings has specified dedicated org/user to run against.
        if: (${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }}!='')
        run: |
          cd ${{matrix.reference_brix}}
          sf org login jwt -o ${{ steps.qlab_config_settings.outputs.ORG_TARGET_USER }} -a dev_target_username -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
          cci org import ${{steps.qlab_config_settings.outputs.ORG_TARGET_USER}} ninja

      - name: export cci session data
        run: |
          cd ${{matrix.reference_brix}}
          cci org info ninja --json > targetdev.json
          tail -n +1 targetdev.json
          tail -n +1 targetdev.json > targetorg.json

      - name: extract the target user
        id: extrattargetorg
        run: |
          cd ${{matrix.reference_brix}}
          echo "extrattargetorg=$(jq '.username' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: extract the target accesstoken
        id: extrattargetaccesstoken
        run: |
          cd ${{matrix.reference_brix}}
          echo "extrattargetaccesstoken=$(jq '.access_token' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: extract the target accesstoken
        id: extrattargetinstanceurl
        run: |
          cd ${{matrix.reference_brix}}
          echo "extrattargetinstanceurl=$(jq '.instance_url' targetorg.json -r)" >> "$GITHUB_OUTPUT"

      - name: set output target user
        id: loadtargetorg
        run: |
          cd ${{matrix.reference_brix}}
          echo "target-org=${{ steps.extrattargetorg.outputs.extrattargetorg }}" >> $GITHUB_OUTPUT

      - name: set output target access token
        id: loadtargetaccesstoken
        run: |
          cd ${{matrix.reference_brix}}
          echo "target-accesstoken=${{ steps.extrattargetaccesstoken.outputs.extrattargetaccesstoken }}" >> $GITHUB_OUTPUT

      - name: set output target instance url
        id: loadtargetintanceurl
        run: |
          cd ${{matrix.reference_brix}}
          echo "target-instanceurl=${{ steps.extrattargetinstanceurl.outputs.extrattargetinstanceurl }}" >> $GITHUB_OUTPUT

      - name: fail details
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        id: cci_failure_details
        run: |
          cd ${{matrix.reference_brix}}
          echo "cci_failure_details=$(cci error info | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: fail status
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          cd ${{matrix.reference_brix}}
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.reference_brix_leafshake_build }}",
              "leafshakebrixname": "${{matrix.reference_brix}}",
              "buildstatus": "Failed",
              "details": "${{ steps.cci_failure_details.outputs.cci_failure_details }}"
          }'

      - name: rfbrowser init setup
        run: |
          cd ${{matrix.reference_brix}}
          pip install protobuf==5.28.1 --force
          rfbrowser init

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        run: |
          cd ${{matrix.reference_brix}}
          cci service list

      - name: Make sure session is valid
        run: |
          cd ${{matrix.reference_brix}}
          cci org info ninja

      - name: Running ${{ matrix.description }} ${{ matrix.leaf_shake_action }}::${{ matrix.reference_brix }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: |
            cd ${{matrix.reference_brix}}
            cci ${{ matrix.leaf_shake_action_type }} run ${{ matrix.leaf_shake_action }}  --org ninja
          on_retry_command: cci error info

      - name: success status
        if: (success() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          cd ${{matrix.reference_brix}}
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "github_repository_id": "${{ github.repository_id }}",
            "brixname": "${{ github.repository }}",
            "leafshakebrixbuildname": "${{ matrix.reference_brix_leafshake_build }}",
            "leafshakebrixname": "${{matrix.reference_brix}}",
            "buildstatus": "Passed",
            "details": ""
                }'

      - name: fail details - final
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        id: cci_failure_details_final
        run: |
          cd ${{matrix.reference_brix}}
          echo "cci_failure_details_final=$(cci error info | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: fail status
        if: (failure() && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: |
          cd ${{matrix.reference_brix}}
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGBrixBuildTrackingService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
              "github_repository_id": "${{ github.repository_id }}",
              "brixname": "${{ github.repository }}",
              "leafshakebrixbuildname": "${{ matrix.reference_brix_leafshake_build }}",
              "leafshakebrixname": "${{matrix.reference_brix}}",
              "buildstatus": "Failed",
              "details": "${{ steps.cci_failure_details_final.outputs.cci_failure_details_final }}"
          }'

  setup_autodeployment_steps:
    needs: [leaf_shake_deployments, build_deployments]
    if: |
      always() &&
      (github.ref_name == 'main' || github.ref_name == 'master') &&
      (needs.leaf_shake_deployments.result == 'success' || needs.leaf_shake_deployments.result == 'skipped' || needs.leaf_shake_deployments.result == 'failed') &&
      ! contains(github.repository, '-7-')
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set ownership
        id: set_ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          echo '${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}' > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        id: qlabs_accesstoken
        run: |
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      #determine if there is a template or instance override defined in qlabs for this build config
      - name: get qlabs auto deploy settings - pipe to jq to file
        id: qlab_config_settings
        run: |
          # call qlabs setting service for this qbrix -> get the json -> pipe to jq
           curl --location --request GET 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings?qbrixid=${{ github.event.repository.name }}' \
           --header 'Content-Type: application/json' \
           --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' | jq > automated_deploy.json

      - name: set the build job matrix for deployments
        id: set-matrix
        run: |
          echo "matrix={\"include\":$(jq -c '.' automated_deploy.json -r)}" >> $GITHUB_OUTPUT

  autodeploy_steps:
    if: |
      always() &&
      (github.ref_name == 'main' || github.ref_name == 'master') &&
      (needs.setup_autodeployment_steps.result == 'success' || needs.setup_autodeployment_steps.result != 'skipped') &&
      ! contains(github.repository, '-7-')
    needs: [setup_autodeployment_steps]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup_autodeployment_steps.outputs.matrix) }}
      max-parallel: 250 #run in parrallel
    steps:
      - uses: actions/checkout@v4

      - name: Update QX
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: qx update

      - name: Core Setup - key for jwt auth
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        id: qlabs_accesstoken
        run: |
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      - name: The automated deploy matrix json contains the list of target org usernames (TSOs Ideally) to deploy against.
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: sf org login jwt -o ${{ matrix.targetusername }} -a dev_target_username -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Set CCI DevHub Username
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: cci service connect devhub --username DEVHUB_ACCT

      - name: force an update
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: cci task run update_qbrix

      - name: rfbrowser init setup
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: |
          pip install protobuf==5.28.1 --force
          rfbrowser init

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: cci service list

      - name: Import the target username into the cci runtime step
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: cci org import ${{ matrix.targetusername }} ninja

      - name: Make sure session is valid
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        run: cci org info ninja

      - name: Running ${{ matrix.description }} ${{ matrix.action }}::${{ matrix.target }}
        if: matrix.targetusername!='' && matrix.ishybrid == 'false'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: cci ${{ matrix.action }} run ${{ matrix.target }}  --org ninja
          on_retry_command: |
            cci error info

      - name: fail details
        if: matrix.targetusername!='' && failure() && ( github.ref_name == 'main' || github.ref_name == 'master') && matrix.ishybrid == 'false'
        id: cci_failure_details
        run: |
          echo "errorlog=$(cci error info | base64 -w 0)" >> $GITHUB_OUTPUT

      - name: fail status
        if: matrix.targetusername!='' && failure() && ( github.ref_name == 'main' || github.ref_name == 'master') && matrix.ishybrid == 'false'
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "qbrixid": "${{ github.event.repository.name }}",
            "targetusername": "${{ matrix.targetusername }}",
            "status": "Failed",
            "notify": "${{ matrix.notify }}",
            "errorlog": "${{ steps.cci_failure_details.outputs.errorlog }}",
            "runurl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": ${{ toJSON(github.event.head_commit.message) }}
          }'

      - name: success status
        if: matrix.targetusername!='' && success() && ( github.ref_name == 'main' || github.ref_name == 'master') && matrix.ishybrid == 'false'
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "qbrixid": "${{ github.event.repository.name }}",
            "targetusername": "${{ matrix.targetusername }}",
            "status": "Success",
            "notify": "${{ matrix.notify }}",
            "runurl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": ${{ toJSON(github.event.head_commit.message) }}
          }'

  hybrid_autodeploy_steps:
    if: |
      always() &&
      (github.ref_name == 'main' || github.ref_name == 'master') &&
      (needs.setup_autodeployment_steps.result == 'success' || needs.setup_autodeployment_steps.result != 'skipped') &&
      ! contains(github.repository, '-7-')
    needs: [setup_autodeployment_steps]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    continue-on-error: true
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup_autodeployment_steps.outputs.matrix) }}
      max-parallel: 250 #run in parrallel
    steps:
      - uses: actions/checkout@v4

      - name: Update QX
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: qx update

      - name: Core Setup - key for jwt auth
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        id: qlabs_accesstoken
        run: |
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      - name: The automated deploy matrix json contains the list of target org usernames (TSOs Ideally) to deploy against.
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: sf org login jwt -o ${{ matrix.targetusername }} -a dev_target_username -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Set CCI DevHub Username
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: cci service connect devhub --username DEVHUB_ACCT

      - name: force an update
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: cci task run update_qbrix

      - name: rfbrowser init setup
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: |
          pip install protobuf==5.28.1 --force
          rfbrowser init

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: cci service list

      - name: Import the target username into the cci runtime step
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: cci org import ${{ matrix.targetusername }} ninja

      - name: Make sure session is valid
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        run: cci org info ninja

      - name: Running ${{ matrix.description }} ${{ matrix.action }}::${{ matrix.target }}
        if: matrix.targetusername!='' && matrix.ishybrid == 'true'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: cci ${{ matrix.action }} run ${{ matrix.target }}  --org ninja
          on_retry_command: |
            cci error info

      - name: fail details
        if: matrix.targetusername!='' && failure() && ( github.ref_name == 'main' || github.ref_name == 'master') && matrix.ishybrid == 'true'
        id: cci_failure_details
        run: |
          echo "errorlog=$(cci error info | base64 -w 0)" >> $GITHUB_OUTPUT

      - name: fail status
        if: matrix.targetusername!='' && failure()  && ( github.ref_name == 'main' || github.ref_name == 'master') && matrix.ishybrid == 'true'
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "qbrixid": "${{ github.event.repository.name }}",
            "targetusername": "${{ matrix.targetusername }}",
            "status": "Failed",
            "notify": "${{ matrix.notify }}",
            "errorlog": "${{ steps.cci_failure_details.outputs.errorlog }}",
            "runurl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": ${{ toJSON(github.event.head_commit.message) }}
          }'

      - name: success status
        if: matrix.targetusername!='' && success() && ( github.ref_name == 'main' || github.ref_name == 'master') && matrix.ishybrid == 'true'
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "qbrixid": "${{ github.event.repository.name }}",
            "targetusername": "${{ matrix.targetusername }}",
            "status": "Success",
            "notify": "${{ matrix.notify }}",
            "runurl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": ${{ toJSON(github.event.head_commit.message) }}
          }'

  metadeploy_publish:
    needs: [build_deployments, leaf_shake_deployments]
    if: |
      always() &&
      (github.ref_name == 'main' || github.ref_name == 'master') &&
      needs.build_deployments.result == 'success' &&
      (needs.leaf_shake_deployments.result == 'success' || needs.leaf_shake_deployments.result == 'skipped' || needs.leaf_shake_deployments.result == 'failed') &&
      ! contains(github.repository, '-7-') &&
      ! contains(github.repository, '-99-')
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: ${{vars.BUILD_BASE_CONTAINER}}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    steps:
      - uses: actions/checkout@v4

      - name: Update QX
        run: qx update

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          echo '${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}' > devhub.key

        # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        id: qlabs_accesstoken
        run: |
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      - name: Set ENV variables
        run: |
          echo "::set-env name=REPO_NAME::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"

      - name: get the build matrices
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixBuildMatrixService' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{"brixname": "${{ env.REPO_NAME }}"}' -o auto_publish.json

      - name: parse build matrices
        id: qlab_config_settings
        run: |
          echo "AUTOPUBLISH=$(jq .auto_publish_brix_store auto_publish.json)" >> "$GITHUB_OUTPUT"
          echo "AUTOPUBLISH=$(jq .auto_publish_brix_store auto_publish.json)" >> "$GITHUB_ENV"

      #display cci version
      - name: cci version
        if: (env.AUTOPUBLISH == 'true' && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: cci version

      #CCI Service List
      - name: cci service list
        if: (env.AUTOPUBLISH == 'true' && ( github.ref_name == 'main' || github.ref_name == 'master'))
        run: cci service list

      - name: metadeploy publish - if applicable
        if: (env.AUTOPUBLISH == 'true' && ( github.ref_name == 'main' || github.ref_name == 'master'))
        continue-on-error: true
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_on: error
          max_attempts: 1
          command: SHORTSHA=$(git rev-parse --short HEAD ) && cci task run metadeploy_publish --commit $SHORTSHA --publish True
          on_retry_command: cci error info