name: CI Validation
on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: Github Environment name to deploy to
        required: true
        default: Test
      fromRef:
        description: Github SHA reference to start from
        required: true
        default: "HEAD^"
      toRef:
        description: Github SHA reference to go up to
        required: true
        default: "HEAD"

jobs:
  delta-deployment:
    name: Delta Validation
    runs-on: ubuntu-20.04
    environment:
      name: ${{ github.event.inputs.environmentName }}
      url: ${{ steps.envtUrl.outputs.url_output }}

    steps:
      - name: Source Branch Name
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.CICD_ACCESS }}

      - name: Triggering event name
        run: echo ${{ github.event_name }}

      - name: Check if workflow_dispatch Triggering Event
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "this is a manually triggered event"
          echo "fromRef="${{ github.event.inputs.fromRef }} >> $GITHUB_ENV
          echo "toRef="${{ github.event.inputs.toRef }} >> $GITHUB_ENV

      - name: Check if not workflow_dispatch Triggering Event
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "This is not a manually triggered workflow event"
          TAG_NAME=$(git describe --tags --abbrev=0)
          TAG_HASH=$(git show-ref -s $TAG_NAME)
          echo 'Using Tag: ' $TAG_NAME ' with Hash: ' $TAG_HASH
          echo "fromRef="$TAG_HASH >> $GITHUB_ENV
          echo "toRef=HEAD" >> $GITHUB_ENV

      - name: Show from and to references
        run: |
          echo "FROM REF: "${{ env.fromRef }}
          echo "TO REF: "${{ env.toRef }}

      - name: Connect to ${{ github.event.inputs.environmentName }} org
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.ORG_AUTH_SECRET }}

      - name: Derive Environment URL
        id: envtUrl
        run: |
          sfdx force:org:display --verbose --json > orgDetails.json
          orgUrl=$(jq '.result.instanceUrl' orgDetails.json | sed 's/^.//;s/.$//')
          accessToken=$(jq '.result.accessToken' orgDetails.json | sed 's/^.//;s/.$//')
          frontDoor='/secur/frontdoor.jsp?sid='
          echo "::set-output name=url_output::"$orgUrl$frontDoor$accessToken

      - name: Install SFDX Plugins
        run: |
          mkdir $HOME/.config/sfdx
          cp .config/sfdx/unsignedPluginAllowList.json $HOME/.config/sfdx/.
          ./scripts/cicd/installSFDXPlugins.sh

      - name: "Create Additive Delta"
        run: ./scripts/cicd/doGitAdditiveDiff.sh ${{ env.fromRef }} ${{ env.toRef }}

      - name: Check additive files exist
        id: additive_files
        uses: andstor/file-existence-action@v1
        with:
          files: "gitUpdates.zip"

      - name: Archive new and modified metadata zip
        uses: actions/upload-artifact@v2
        if: steps.additive_files.outputs.files_exists == 'true'
        with:
          name: new-modified-files.zip
          path: gitUpdates.zip

      - name: Archive new and modified metadata text file
        uses: actions/upload-artifact@v2
        if: steps.additive_files.outputs.files_exists == 'true'
        with:
          name: new-modified-files.txt
          path: new-modified-files.txt

      - name: "Create Destructive Delta"
        run: ./scripts/cicd/doGitDestructiveDiff.sh ${{ env.fromRef }} ${{ env.toRef }}

      - name: Check destructive files exist
        id: destructive_files
        uses: andstor/file-existence-action@v1
        with:
          files: "gitDeletions.zip"

      - name: Archive deleted metadata zip
        uses: actions/upload-artifact@v2
        if: steps.destructive_files.outputs.files_exists == 'true'
        with:
          name: deleted-files.zip
          path: gitDeletions.zip

      - name: Archive deleted metadata text file
        uses: actions/upload-artifact@v2
        if:  steps.destructive_files.outputs.files_exists == 'true'
        with:
          name: deleted-files.txt
          path: deleted-files.txt

      - name: Check pre-deployment script exist
        id: preDeploymentScript
        uses: andstor/file-existence-action@v1
        with:
          files: "scripts/deployment/preDeploymentSteps.sh"

      - name: "Run Pre Deployment Script"
        if: steps.preDeploymentScript.outputs.files_exists == 'true'
        run: ./scripts/deployment/preDeploymentSteps.sh

      - name: 'Validate against ${{ github.event.inputs.environmentName }}'
        if: steps.additive_files.outputs.files_exists == 'true'
        run: sfdx force:source:deploy -p "deltaDeploy/force-app" --checkonly

#      - name: 'Run Destructive Deploy Validation Prod'
#        if:  steps.destructive_files.outputs.files_exists == 'true'
#        run: sfdx force:mdapi:deploy -d deltaDestructiveDeployMeta -w 30 --checkonly
