name: QBrix-Automated-Push-Deploy
on:
  push:
    branches: ["main"]

  workflow_dispatch:
env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.QBRIX_CUMULUSCI_SERVICE_github }}
  SFDX_CLIENT_ID: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  SFDX_HUB_KEY: ${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}
  DEVHUBCONSUMERKEY: ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}
  DEVHUBJWTKEYFILE: devhub.key
  GITHUB_PAT: ${{ secrets.QBRIX_GITHUB_PAT}}
  USE_TEMPLATE: true
  TEMPLATEID: LATEST
  TEMPLATE_INSTANCE: NA135
  SFDX_DISABLE_DNS_CHECK: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  BUILD_SUFFIX: QBrix-Automated-Push-Deploy
  QBRIX_SYSTEM_ID: AUTO_DEPLOY
  SF_USE_PROGRESS_BAR: false
  QSR_ENDPOINT: ${{ secrets.QSR_ENDPOINT }}
  QSR_JWT_SIGNING_SECRET: ${{ secrets.QSR_JWT_SIGNING_SECRET }}

jobs:
  collection_deployment_steps:
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: "ghcr.io/${{ github.repository_owner }}/qbrix-base-container-quasar:latest"
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set ownership
        id: set_ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          echo '${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}' > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        id: qlabs_accesstoken
        run: |
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      #determine if there is a template or instance override defined in qlabs for this build config
      - name: get qlabs auto deploy settings - pipe to jq to file
        id: qlab_config_settings
        run: |
          # call qlabs setting service for this qbrix -> get the json -> pipe to jq
           curl --location --request GET 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings?qbrixid=${{ github.event.repository.name }}' \
           --header 'Content-Type: application/json' \
           --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' | jq > automated_deploy.json

      - name: set the build job matrix for deployments
        id: set-matrix
        run: |
          echo "matrix={\"include\":$(jq -c '.' automated_deploy.json -r)}" >> $GITHUB_OUTPUT

  qbrix_deployments:
    needs: [collection_deployment_steps]
    runs-on: sfdc-qbranch-nextgen-ubuntu
    container:
      image: "ghcr.io/${{ github.repository_owner }}/qbrix-base-container-quasar:latest"
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.QBRIX_CONTAINER_PUBLISH_GITHUB_PAT}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.collection_deployment_steps.outputs.matrix) }}
      max-parallel: 250 #run in parrallel
    steps:
      - uses: actions/checkout@v4

      - name: Core Setup - key for jwt auth
        if: matrix.targetusername!=''
        run: echo "${{ secrets.QBRIX_DEVHUB_PRIVATE_KEY }}" > devhub.key

      # We will use a common app with a common key -
      - name: Create SFDX Session for QLABS Service Account
        if: matrix.targetusername!=''
        run: sf org login jwt -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Extract the accesstoken
        if: matrix.targetusername!=''
        run: sf org display -o ${{ secrets.QBRIX_QLABS_SERVICE_ACCOUNT }} --json > qlab_tmp.json

      - name: extract the accesstoken for qlabs
        if: matrix.targetusername!=''
        id: qlabs_accesstoken
        run: |
          echo "qlabs_accesstoken=$(jq '.result.accessToken' qlab_tmp.json -r)" >> "$GITHUB_OUTPUT"

      - name: The automated deploy matrix json contains the list of target org usernames (TSOs Ideally) to deploy against.
        if: matrix.targetusername!=''
        run: sf org login jwt -o ${{ matrix.targetusername }} -a dev_target_username -d -f devhub.key -i ${{ secrets.QBRIX_DEVHUB_CONSUMER_KEY }}

      - name: Set CCI DevHub Username
        if: matrix.targetusername!=''
        run: cci service connect devhub --username DEVHUB_ACCT

      - name: force an update
        if: matrix.targetusername!=''
        run: cci task run update_qbrix

      - name: rfbrowser init setup
        if: matrix.targetusername!=''
        run: rfbrowser init

      # CCI Service List - we should have all 3 connected now: persistant, github (via env var) and devhub
      - name: All connected services
        if: matrix.targetusername!=''
        run: cci service list

      - name: Import the target username into the cci runtime step
        if: matrix.targetusername!=''
        run: cci org import ${{ matrix.targetusername }} dev

      - name: Make sure session is valid
        if: matrix.targetusername!=''
        run: cci org info dev

      - name: Running ${{ matrix.description }} ${{ matrix.action }}::${{ matrix.target }}
        if: matrix.targetusername!=''
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1440
          retry_on: error
          max_attempts: 2
          command: cci ${{ matrix.action }} run ${{ matrix.target }}  --org dev
          on_retry_command: cci error info

      - name: fail details
        if: ${{ matrix.targetusername!='' && failure() && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        id: cci_failure_details
        run: |
          echo "errorlog=$(cci error info | base64 -w 0)" >> $GITHUB_OUTPUT

      - name: fail status
        if: ${{  matrix.targetusername!='' && failure() && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "qbrixid": "${{ github.event.repository.name }}",
            "status": "Failed",
            "notify": "${{ matrix.notify }}",
            "errorlog": "${{ steps.cci_failure_details.outputs.errorlog }}",
            "runurl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": ${{ toJSON(github.event.head_commit.message) }}
          }'

      - name: success status
        if: ${{ matrix.targetusername!='' && success() && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        run: |
          curl --location 'https://qlabs-org.my.salesforce.com/services/apexrest/NGQBrixAutoDeploySettings' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ steps.qlabs_accesstoken.outputs.qlabs_accesstoken }}' \
          --data '{
            "qbrixid": "${{ github.event.repository.name }}",
            "status": "Success",
            "notify": "${{ matrix.notify }}",
            "runurl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": ${{ toJSON(github.event.head_commit.message) }}
          }'
